/*
 * KeyCodes.cpp
 *
 *  Created on: Apr 17, 2016
 *      Author: root
 */

#include "KeyCodes.h"
#include <map>


static const std::map<KeyboardKey, KeyCode> KeyToHIDUsageIdMap {
	{KeyboardKey::a/*, A*/, 0x04},
	{KeyboardKey::b/*, B*/, 0x05},
	{KeyboardKey::c/*, C*/, 0x06},
	{KeyboardKey::d/*, D*/, 0x07},
	{KeyboardKey::e/*, E*/, 0x08},
	{KeyboardKey::f/*, F*/, 0x09},
	{KeyboardKey::g/*, G*/, 0x0A},
	{KeyboardKey::h/*, H*/, 0x0B},
	{KeyboardKey::i/*, I*/, 0x0C},
	{KeyboardKey::j/*, J*/, 0x0D},
	{KeyboardKey::k/*, K*/, 0x0E},
	{KeyboardKey::l/*, L*/, 0x0F},
	{KeyboardKey::m/*, M*/, 0x10},
	{KeyboardKey::n/*, N*/, 0x11},
	{KeyboardKey::o/*, O*/, 0x12},
	{KeyboardKey::p/*, P*/, 0x13},
	{KeyboardKey::q/*, Q*/, 0x14},
	{KeyboardKey::r/*, R*/, 0x15},
	{KeyboardKey::s/*, S*/, 0x16},
	{KeyboardKey::t/*, T*/, 0x17},
	{KeyboardKey::u/*, U*/, 0x18},
	{KeyboardKey::v/*, V*/, 0x19},
	{KeyboardKey::w/*, W*/, 0x1A},
	{KeyboardKey::x/*, X*/, 0x1B},
	{KeyboardKey::y/*, Y*/, 0x1C},
	{KeyboardKey::z/*, Z*/, 0x1D},
	{KeyboardKey::num1/*, Bang*/, 0x1E},
	{KeyboardKey::num2/*, At*/, 0x1F},
	{KeyboardKey::num3/*, Sharp*/, 0x20},
	{KeyboardKey::num4/*, Dollar*/, 0x21},
	{KeyboardKey::num5/*, Percent*/, 0x22},
	{KeyboardKey::num6/*, Xor*/, 0x23},
	{KeyboardKey::num7/*, And*/, 0x24},
	{KeyboardKey::num8/*, Star*/, 0x25},
	{KeyboardKey::num9/*, LeftParenthesis*/, 0x26},
	{KeyboardKey::num0/*, RightParenthesis*/, 0x27},
	{KeyboardKey::Return, 0x28},
	{KeyboardKey::Escape, 0x29},
	{KeyboardKey::Backspace, 0x2A},
	{KeyboardKey::Tab, 0x2B},
	{KeyboardKey::Space, 0x2C},
	{KeyboardKey::Minus/*, Underscore,*/, 0x2D},
	{KeyboardKey::Equal/*, Plus*/, 0x2E},
	{KeyboardKey::LeftBracket/*, LeftBrace*/, 0x2F},
	{KeyboardKey::RightBracket/*, RightBrace*/, 0x30},
	{KeyboardKey::BackSlash/*, VerticalLine*/, 0x31},

	{KeyboardKey::Semicolon/*, Colon*/, 0x33},
	{KeyboardKey::Quote/*, DoubleQuote*/, 0x34},
	{KeyboardKey::BackQuote/*, Tilda*/, 0x35},
	{KeyboardKey::Comma/*, LT*/, 0x36},
	{KeyboardKey::Dot/*, GT*/, 0x37},
	{KeyboardKey::Slash/*, Question*/, 0x38},
	{KeyboardKey::CapsLock, 0x39},
	{KeyboardKey::F1, 0x3A},
	{KeyboardKey::F2, 0x3B},
	{KeyboardKey::F3, 0x3C},
	{KeyboardKey::F4, 0x3D},
	{KeyboardKey::F5, 0x3E},
	{KeyboardKey::F6, 0x3F},
	{KeyboardKey::F7, 0x40},
	{KeyboardKey::F8, 0x41},
	{KeyboardKey::F9, 0x42},
	{KeyboardKey::F10, 0x43},
	{KeyboardKey::F11, 0x44},
	{KeyboardKey::F12, 0x45},
	{KeyboardKey::PrintScreen, 0x46},
	{KeyboardKey::ScrollLock, 0x47},
	{KeyboardKey::Break, 0x48},
	{KeyboardKey::Pause, 0x48},
	{KeyboardKey::Insert, 0x49},
	{KeyboardKey::Home, 0x4A},
	{KeyboardKey::PageUp, 0x4B},
	{KeyboardKey::Delete, 0x4C},
	{KeyboardKey::End, 0x4D},
	{KeyboardKey::PageDown, 0x4E},
	{KeyboardKey::RightArrow, 0x4F},
	{KeyboardKey::LeftArrow, 0x50},
	{KeyboardKey::DownArrow, 0x51},
	{KeyboardKey::UpArrow, 0x52},
	{KeyboardKey::NumLock, 0x53},
	{KeyboardKey::KeypadSlash, 0x54},
	{KeyboardKey::KeypadStar, 0x55},
	{KeyboardKey::KeypadMinus, 0x56},
	{KeyboardKey::KeypadPlus, 0x57},
	{KeyboardKey::KeypadEnter, 0x58},
	{KeyboardKey::Keypad1/*, KeypadEnd*/, 0x59},
	{KeyboardKey::Keypad2/*, KeypadDown*/, 0x5A},
	{KeyboardKey::Keypad3/*, KeypadPageDown*/, 0x5B},
	{KeyboardKey::Keypad4/*, KeypadLeft*/, 0x5C},
	{KeyboardKey::Keypad5, 0x5D},
	{KeyboardKey::Keypad6/*, KeypadRight*/, 0x5E},
	{KeyboardKey::Keypad7/*, KeypadHome*/, 0x5F},
	{KeyboardKey::Keypad8/*, KeypadUp*/, 0x60},
 	{KeyboardKey::Keypad9/*, KeypadPageUp*/, 0x61},
	{KeyboardKey::Keypad0/*, KeypadInstert*/, 0x62},
	{KeyboardKey::KeypadDot/*, KeypadDelete*/, 0x63},

	{KeyboardKey::LeftControl, 0xE0},
	{KeyboardKey::LeftShift, 0xE1},
	{KeyboardKey::LeftAlt, 0xE2},
	{KeyboardKey::LeftGUI, 0xE3},
	{KeyboardKey::RightControl, 0xE4},
	{KeyboardKey::RightShift, 0xE5},
	{KeyboardKey::RightAlt, 0xE6},
	{KeyboardKey::RightGUI, 0xE7},
};


static const std::map<KeyboardKey, KeyCodesVec> KeyToPS2Set1MakeScancodesMap {
	{KeyboardKey::a/*, A*/, {0x1E}},
	{KeyboardKey::b/*, B*/, {0x30}},
	{KeyboardKey::c/*, C*/, {0x2E}},
	{KeyboardKey::d/*, D*/, {0x20}},
	{KeyboardKey::e/*, E*/, {0x12}},
	{KeyboardKey::f/*, F*/, {0x21}},
	{KeyboardKey::g/*, G*/, {0x22}},
	{KeyboardKey::h/*, H*/, {0x23}},
	{KeyboardKey::i/*, I*/, {0x17}},
	{KeyboardKey::j/*, J*/, {0x24}},
	{KeyboardKey::k/*, K*/, {0x25}},
	{KeyboardKey::l/*, L*/, {0x26}},
	{KeyboardKey::m/*, M*/, {0x32}},
	{KeyboardKey::n/*, N*/, {0x31}},
	{KeyboardKey::o/*, O*/, {0x18}},
	{KeyboardKey::p/*, P*/, {0x19}},
	{KeyboardKey::q/*, Q*/, {0x10}},
	{KeyboardKey::r/*, R*/, {0x13}},
	{KeyboardKey::s/*, S*/, {0x1F}},
	{KeyboardKey::t/*, T*/, {0x14}},
	{KeyboardKey::u/*, U*/, {0x16}},
	{KeyboardKey::v/*, V*/, {0x2F}},
	{KeyboardKey::w/*, W*/, {0x11}},
	{KeyboardKey::x/*, X*/, {0x2D}},
	{KeyboardKey::y/*, Y*/, {0x15}},
	{KeyboardKey::z/*, Z*/, {0x2C}},
	{KeyboardKey::num1/*, Bang*/, {0x02}},
	{KeyboardKey::num2/*, At*/, {0x03}},
	{KeyboardKey::num3/*, Sharp*/, {0x04}},
	{KeyboardKey::num4/*, Dollar*/, {0x05}},
	{KeyboardKey::num5/*, Percent*/, {0x06}},
	{KeyboardKey::num6/*, Xor*/, {0x07}},
	{KeyboardKey::num7/*, And*/, {0x08}},
	{KeyboardKey::num8/*, Star*/, {0x09}},
	{KeyboardKey::num9/*, LeftParenthesis*/, {0x0A}},
	{KeyboardKey::num0/*, RightParenthesis*/, {0x0B}},
	{KeyboardKey::Return, {0x1C}},
	{KeyboardKey::Escape, {0x01}},
	{KeyboardKey::Backspace, {0x0E}},
	{KeyboardKey::Tab, {0x0F}},
	{KeyboardKey::Space, {0x39}},
	{KeyboardKey::Minus/*, Underscore,*/, {0x0C}},
	{KeyboardKey::Equal/*, Plus*/, {0x0D}},
	{KeyboardKey::LeftBracket/*, LeftBrace*/, {0x1A}},
	{KeyboardKey::RightBracket/*, RightBrace*/, {0x1B}},
	{KeyboardKey::BackSlash/*, VerticalLine*/, {0x2B}},
	{KeyboardKey::Semicolon/*, Colon*/, {0x27}},
	{KeyboardKey::Quote/*, DoubleQuote*/, {0x28}},
	{KeyboardKey::BackQuote/*, Tilda*/, {0x29}},
	{KeyboardKey::Comma/*, LT*/, {0x33}},
	{KeyboardKey::Dot/*, GT*/, {0x34}},
	{KeyboardKey::Slash/*, Question*/, {0x35}},
	{KeyboardKey::CapsLock, {0x3A}},
	{KeyboardKey::F1, {0x3B}},
	{KeyboardKey::F2, {0x3C}},
	{KeyboardKey::F3, {0x3D}},
	{KeyboardKey::F4, {0x3E}},
	{KeyboardKey::F5, {0x3F}},
	{KeyboardKey::F6, {0x40}},
	{KeyboardKey::F7, {0x41}},
	{KeyboardKey::F8, {0x42}},
	{KeyboardKey::F9, {0x43}},
	{KeyboardKey::F10, {0x44}},
	{KeyboardKey::F11, {0x57}},
	{KeyboardKey::F12, {0x58}},
	{KeyboardKey::PrintScreen, {0xE0, 0x37}},
	{KeyboardKey::ScrollLock, {0x46}},
	{KeyboardKey::Break, {0xE0, 0x46,   0xE0, 0xC6}},
	{KeyboardKey::Pause, {0xE1, 0x1D, 0x45,   0xE1, 0x9D, 0xC5}},
	{KeyboardKey::Insert, {0xE0, 0x52}},
	{KeyboardKey::Home, {0xE0, 0x47}},
	{KeyboardKey::PageUp, {0xE0, 0x49}},
	{KeyboardKey::Delete, {0xE0, 0x53}},
	{KeyboardKey::End, {0xE0, 0x4F}},
	{KeyboardKey::PageDown, {0xE0, 0x51}},
	{KeyboardKey::RightArrow, {0xE0, 0x4D}},
	{KeyboardKey::LeftArrow, {0xE0, 0x4B}},
	{KeyboardKey::DownArrow, {0xE0, 0x50}},
	{KeyboardKey::UpArrow, {0xE0, 0x48}},
	{KeyboardKey::NumLock, {0x45}},
	{KeyboardKey::KeypadSlash, {0xE0, 0x35}},
	{KeyboardKey::KeypadStar, {0x37}},
	{KeyboardKey::KeypadMinus, {0x4A}},
	{KeyboardKey::KeypadPlus, {0x4E}},
	{KeyboardKey::KeypadEnter, {0xE0, 0x1C}},
	{KeyboardKey::Keypad1/*, KeypadEnd*/, {0x4F}},
	{KeyboardKey::Keypad2/*, KeypadDown*/, {0x50}},
	{KeyboardKey::Keypad3/*, KeypadPageDown*/, {0x51}},
	{KeyboardKey::Keypad4/*, KeypadLeft*/, {0x4B}},
	{KeyboardKey::Keypad5, {0x4C}},
	{KeyboardKey::Keypad6/*, KeypadRight*/, {0x4D}},
	{KeyboardKey::Keypad7/*, KeypadHome*/, {0x47}},
	{KeyboardKey::Keypad8/*, KeypadUp*/, {0x48}},
 	{KeyboardKey::Keypad9/*, KeypadPageUp*/, {0x49}},
	{KeyboardKey::Keypad0/*, KeypadInstert*/, {0x52}},
	{KeyboardKey::KeypadDot/*, KeypadDelete*/, {0x53}},
	{KeyboardKey::LeftControl, {0x1D}},
	{KeyboardKey::LeftShift, {0x2A}},
	{KeyboardKey::LeftAlt, {0x38}},
	{KeyboardKey::LeftGUI, {0xE0, 0x5B}},
	{KeyboardKey::RightControl, {0xE0, 0x1D}},
	{KeyboardKey::RightShift, {0x36}},
	{KeyboardKey::RightAlt, {0xE0, 0x38}},
	{KeyboardKey::RightGUI, {0xE0, 0x5C}},
};

static const std::map<KeyboardKey, KeyCodesVec> KeyToPS2Set1BreakScancodesMap {
	{KeyboardKey::a/*, A*/, {0x9E}},
	{KeyboardKey::b/*, B*/, {0xB0}},
	{KeyboardKey::c/*, C*/, {0xAE}},
	{KeyboardKey::d/*, D*/, {0xA0}},
	{KeyboardKey::e/*, E*/, {0x92}},
	{KeyboardKey::f/*, F*/, {0xA1}},
	{KeyboardKey::g/*, G*/, {0xA2}},
	{KeyboardKey::h/*, H*/, {0xA3}},
	{KeyboardKey::i/*, I*/, {0x97}},
	{KeyboardKey::j/*, J*/, {0xA4}},
	{KeyboardKey::k/*, K*/, {0xA5}},
	{KeyboardKey::l/*, L*/, {0xA6}},
	{KeyboardKey::m/*, M*/, {0xB2}},
	{KeyboardKey::n/*, N*/, {0xB1}},
	{KeyboardKey::o/*, O*/, {0x98}},
	{KeyboardKey::p/*, P*/, {0x99}},
	{KeyboardKey::q/*, Q*/, {0x90}},
	{KeyboardKey::r/*, R*/, {0x93}},
	{KeyboardKey::s/*, S*/, {0x9F}},
	{KeyboardKey::t/*, T*/, {0x94}},
	{KeyboardKey::u/*, U*/, {0x96}},
	{KeyboardKey::v/*, V*/, {0xAF}},
	{KeyboardKey::w/*, W*/, {0x91}},
	{KeyboardKey::x/*, X*/, {0xAD}},
	{KeyboardKey::y/*, Y*/, {0x95}},
	{KeyboardKey::z/*, Z*/, {0xAC}},
	{KeyboardKey::num1/*, Bang*/, {0x82}},
	{KeyboardKey::num2/*, At*/, {0x83}},
	{KeyboardKey::num3/*, Sharp*/, {0x84}},
	{KeyboardKey::num4/*, Dollar*/, {0x85}},
	{KeyboardKey::num5/*, Percent*/, {0x86}},
	{KeyboardKey::num6/*, Xor*/, {0x87}},
	{KeyboardKey::num7/*, And*/, {0x88}},
	{KeyboardKey::num8/*, Star*/, {0x89}},
	{KeyboardKey::num9/*, LeftParenthesis*/, {0x8A}},
	{KeyboardKey::num0/*, RightParenthesis*/, {0x8B}},
	{KeyboardKey::Return, {0x9C}},
	{KeyboardKey::Escape, {0x81}},
	{KeyboardKey::Backspace, {0x8E}},
	{KeyboardKey::Tab, {0x8F}},
	{KeyboardKey::Space, {0xB9}},
	{KeyboardKey::Minus/*, Underscore,*/, {0x8C}},
	{KeyboardKey::Equal/*, Plus*/, {0x8D}},
	{KeyboardKey::LeftBracket/*, LeftBrace*/, {0x9A}},
	{KeyboardKey::RightBracket/*, RightBrace*/, {0x9B}},
	{KeyboardKey::BackSlash/*, VerticalLine*/, {0xAB}},
	{KeyboardKey::Semicolon/*, Colon*/, {0xA7}},
	{KeyboardKey::Quote/*, DoubleQuote*/, {0xA8}},
	{KeyboardKey::BackQuote/*, Tilda*/, {0xA9}},
	{KeyboardKey::Comma/*, LT*/, {0xB3}},
	{KeyboardKey::Dot/*, GT*/, {0xB4}},
	{KeyboardKey::Slash/*, Question*/, {0xB5}},
	{KeyboardKey::CapsLock, {0xBA}},
	{KeyboardKey::F1, {0xBB}},
	{KeyboardKey::F2, {0xBC}},
	{KeyboardKey::F3, {0xBD}},
	{KeyboardKey::F4, {0xBE}},
	{KeyboardKey::F5, {0xBF}},
	{KeyboardKey::F6, {0xC0}},
	{KeyboardKey::F7, {0xC1}},
	{KeyboardKey::F8, {0xC2}},
	{KeyboardKey::F9, {0xC3}},
	{KeyboardKey::F10, {0xC4}},
	{KeyboardKey::F11, {0xD7}},
	{KeyboardKey::F12, {0xD8}},
	{KeyboardKey::PrintScreen, {0xE0, 0xB7}},
	{KeyboardKey::ScrollLock, {0xC6}},
	//{KeyboardKey::Break, {0xE0, 0x46,   0xE0, 0xC6}},
	//{KeyboardKey::Pause, {0xE1, 0x1D, 0x45,   0xE1, 0x9D, 0xC5}},
	{KeyboardKey::Insert, {0xE0, 0xD2}},
	{KeyboardKey::Home, {0xE0, 0xC7}},
	{KeyboardKey::PageUp, {0xE0, 0xC9}},
	{KeyboardKey::Delete, {0xE0, 0xD3}},
	{KeyboardKey::End, {0xE0, 0xCF}},
	{KeyboardKey::PageDown, {0xE0, 0xD1}},
	{KeyboardKey::RightArrow, {0xE0, 0xCD}},
	{KeyboardKey::LeftArrow, {0xE0, 0xCB}},
	{KeyboardKey::DownArrow, {0xE0, 0xD0}},
	{KeyboardKey::UpArrow, {0xE0, 0xC8}},
	{KeyboardKey::NumLock, {0xC5}},
	{KeyboardKey::KeypadSlash, {0xE0, 0xB5}},
	{KeyboardKey::KeypadStar, {0xB7}},
	{KeyboardKey::KeypadMinus, {0xCA}},
	{KeyboardKey::KeypadPlus, {0xCE}},
	{KeyboardKey::KeypadEnter, {0xE0, 0x9C}},
	{KeyboardKey::Keypad1/*, KeypadEnd*/, {0xCF}},
	{KeyboardKey::Keypad2/*, KeypadDown*/, {0xD0}},
	{KeyboardKey::Keypad3/*, KeypadPageDown*/, {0xD1}},
	{KeyboardKey::Keypad4/*, KeypadLeft*/, {0xCB}},
	{KeyboardKey::Keypad5, {0xCC}},
	{KeyboardKey::Keypad6/*, KeypadRight*/, {0xCD}},
	{KeyboardKey::Keypad7/*, KeypadHome*/, {0xC7}},
	{KeyboardKey::Keypad8/*, KeypadUp*/, {0xC8}},
 	{KeyboardKey::Keypad9/*, KeypadPageUp*/, {0xC9}},
	{KeyboardKey::Keypad0/*, KeypadInstert*/, {0xD2}},
	{KeyboardKey::KeypadDot/*, KeypadDelete*/, {0xD3}},
	{KeyboardKey::LeftControl, {0x9D}},
	{KeyboardKey::LeftShift, {0xAA}},
	{KeyboardKey::LeftAlt, {0xB8}},
	{KeyboardKey::LeftGUI, {0xE0, 0xDB}},
	{KeyboardKey::RightControl, {0xE0, 0x9D}},
	{KeyboardKey::RightShift, {0xB6}},
	{KeyboardKey::RightAlt, {0xE0, 0xB8}},
	{KeyboardKey::RightGUI, {0xE0, 0xDC}},
};


KeyCodesVec KeyCodesConverter::ConvertToPS2Set1Scancodes(KeyboardKey key, bool isPressed)
{
	if (isPressed) {
		return KeyToPS2Set1MakeScancodesMap.at(key);
	}

	return KeyToPS2Set1BreakScancodesMap.at(key);
}


KeyCode KeyCodesConverter::ConvertToHidUsageId(KeyboardKey key)
{
	return KeyToHIDUsageIdMap.at(key);
}

//TODO: Create reverse map from KeyToHIDUsageIdMap
KeyboardKey KeyCodesConverter::ConvertFromHidUsageId(KeyCode hid)
{
	for (const auto& p: KeyToHIDUsageIdMap) {
		if (p.second == hid) {
			return p.first;
		}
	}

	return KeyboardKey::NONE;
}
